apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
        - env:
          - name: WORDPRESS_DB_HOST
            value: 10.105.145.38
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: abcd@123
          - name: WORDPRESS_DB_NAME
            value: wordpress
          image: wordpress
          name: wordpress
          ports:
          - containerPort: 80

status: {}
